plugins {
    id 'java'
     id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'

    id 'info.solidsoft.pitest' version '1.15.0'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'
description = 'MTPOGr'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.graphwalker:graphwalker-java:4.3.3'
    testImplementation 'org.graphwalker:graphwalker-core:4.3.3'
    testImplementation 'org.graphwalker:graphwalker-dsl:4.3.3'
    testImplementation 'org.graphwalker:graphwalker-io:4.3.3'
    testImplementation 'com.code-intelligence:jazzer-junit:0.21.0'

    testImplementation 'nz.ac.waikato.modeljunit:modeljunit:2.5'
    implementation 'com.google.code.gson:gson:2.8.8'
    pitest 'org.pitest:pitest-junit5-plugin:1.2.1'
            implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.springframework.statemachine:spring-statemachine-core:3.2.1'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // Стартер для работы с данными через JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    // База данных (временная, для примера)
    runtimeOnly 'com.h2database:h2'

    // Стартер для тестов
    testImplementation 'org.springframework.boot:spring-boot-starter-test'


}
task runGraphWalker(type: JavaExec) {
    main = '-jar'
    args = ['graphwalker-cli-4.3.3(1).jar', 'offline', '-m', 'C:\\Users\\Администратор\\Downloads\\test(1).json', 'random(edge_coverage(100))', '--output', 'build/reports/graphwalker.html']
}
pitest {
    reportDir           = file("${layout.buildDirectory.get()}/reports/pitest")
    junit5PluginVersion = '1.2.1'
    targetClasses   = ['org.example.*']     // пакеты для мутационного тестирования
    targetTests     = ['org.example.*']     // пакеты с тестами
    mutators        = ['DEFAULTS']          // набор мутаторов
    outputFormats   = ['HTML', 'XML']       // форматы отчётов
    timestampedReports = false              // без временных меток в папке
    threads         = 4                     // параллельность
    //coverageThreshold = 90                  // минимальный % покрытия
}
tasks.named('test') {
    useJUnitPlatform()
    maxParallelForks = 1
    setForkEvery(0)
    jvmArgs = ['-Xmx512m']
}
